### ISSUE TITLE
graph colors are not changing

### ISSUE THREAD

**Issue by adsick** [mgalgs/gnome-shell-system-monitor-applet#10]
![image](https://user-images.githubusercontent.com/24528839/140910845-d7c09693-9681-4003-871b-5c9cb49ff918.png)

**Comment by mgalgs** [comment]
Hey there, this repo only deals with packaging and uploading this extension. You'll want to report this to upstream: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet

Thanks!
