### ISSUE TITLE
Feature Idea: Enhanced 'Compact Display'

### ISSUE THREAD

**Issue by BillyCroan** [mgalgs/gnome-shell-system-monitor-applet#20]
When 'Compact Display' is checked, print the name of each graph over a (select-able) corner of the graph itself.

This will reduce much of the space needed to display labeled graphs.

Additionally, if percent is visible, display it below or above the name label of each graph.

**Comment by mgalgs** [comment]
Hey there, interesting idea! But this is the wrong repo to make requests. Please see this snippet from the top-level readme:

> Any issues, bug reports, feature requests, etc. for the extension itself should be submitted to the [upstream repo](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet), but build/sync issues should be reported here.
