### ISSUE TITLE
Problem downloading extension

### ISSUE THREAD

**Issue by Ultimatedude10** [mgalgs/gnome-shell-system-monitor-applet#23]
Error: "Tried to construct an object without a GType"

Pop_os 22.04

**Comment by mgalgs** [comment]
As per [the readme](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/master/README.md), all issues should be submitted to [the upstream project](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet). Thanks!
