### ISSUE TITLE
Reduce the frequency

### ISSUE THREAD

**Issue by chrishna1** [mgalgs/gnome-shell-system-monitor-applet#24]
Thanks for automating the task of updating the extension. It did help me because the original extension was showing "incompatible".

But I just saw that it's being updated every hour, I don't think that level of bleeding edge is required for this. Running it once or twice a day would be enough. Saying it as a just another carbon emission conscious person. Anyway, the final choice is yours. 

Feel free to close this issue after you've seen it.

**Comment by mgalgs** [comment]
Hey the carbon emission angle is interesting... I don't think 30 seconds of runtime each hour is going to light the atmosphere on fire :wink: but I see your point. Reducing the frequency to 6 hours. Thanks!
