### ISSUE TITLE
Error: Tried to construct an object without a GType

### ISSUE THREAD

**Issue by chapuis** [mgalgs/gnome-shell-system-monitor-applet#31]
Hello,

I just upgraded my linux to Ubuntu 22.04.1 LTS (from Ubuntu 18). I tried to install my preferred gnome shell extension, and it does not work. I get the following error in syslog:

Feb  9 14:03:03 opale6 gnome-shell[1565]: JS ERROR: Extension system-monitor-next@paradoxxx.zero.gmail.com: Error: Tried to construct an object without a GType#012ModalDialog@resource:///org/gnome/shell/ui/modalDialog.js:32:4#012SystemMonitor_smDialog@/home/olivier/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:287:9#012enable@/home/olivier/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2414:23#012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:183:32#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:384:26#012_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35#012Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:132:41

thanks,
Olivier

**Comment by jasqs** [comment]
Hi,

the same problem from me on a fresh Ubuntu 22.04.1 installation. Any ideas?

**Comment by mgalgs** [comment]
Have you tried restarting your session? Either logout/login or do `Alt-f2 r`. For some reason this is sometimes necessary after installing.

**Comment by jasqs** [comment]
Sure, I was restarting. This was a fresh installation and I have been restarting many times.

**Comment by mgalgs** [comment]
Did you install all of the system dependencies as per the README? If you [search the upstream issue tracker](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues?q=is%3Aissue+Tried+to+construct+an+object+without+a+GType) for this error message you'll see quite a few people with a similar error, here's one example: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/746 (resolution was to install the system dependencies)

**Comment by jasqs** [comment]
Sorry, I forgot to write that I solved the problem. Indeed, I had problems because I had not installed the dependencies. I have run:

sudo apt install gir1.2-gtop-2.0 gir1.2-nm-1.0 gir1.2-clutter-1.0 gnome-system-monitor

as you suggested in the repo's README - this solved the issue. 

thanks for help

**Comment by mgalgs** [comment]
Excellent!
