### ISSUE TITLE
JS error in system logs

### ISSUE THREAD

**Issue by giedriusStan** [mgalgs/gnome-shell-system-monitor-applet#35]
I use Arch and I get this error message every second:

```
JS ERROR: Gio.IOErrorEnum: Error reading from file: No data available
                                        refresh/<@/home/giedrius/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2113:35
```

I use the following command to view the logs in real time:

journalctl --follow

**Comment by ZimbiX** [comment]
That's annoying that the message doesn't give any more context.

By the line number, it looks like this is to do with reading the thermal sensor file:

https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/68f51c5b83e9bdbec08544273d9bf7d2228e2e63/system-monitor%40paradoxxx.zero.gmail.com/extension.js#L2108-L2115

This code is reading the file at the path stored in the `thermal-sensor-file` setting.

I have my thermal sensor dropdown set to 'thinkpad - CPU', and so the resulting path setting is:

```
$ dconf dump /org/gnome/shell/extensions/system-monitor/ | grep thermal-sensor-file
thermal-sensor-file='/sys/class/hwmon/hwmon4/temp1_input'
```

Try another option for the thermal sensor?

**Comment by mgalgs** [comment]
@giedriusStan Can you please file this with [upstream](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet) for tracking? We're still not actually making fixes in this repo, those should happen in upstream.
