### ISSUE TITLE
"meta is null"

### ISSUE THREAD

**Issue by nanbuwks** [mgalgs/gnome-shell-system-monitor-applet#36]
This should be posted to `paradoxxxzero/gnome-shell-system-monitor-applet`.
However, system-monitor has not worked on Ubuntu 22.04 for a long time.
So I think it's appropriate to post it here.

I have been using system-monitor-next on Ubuntu 22.04 for a long time.
Today I installed Ubuntu 22.04 and system-monitor-next on a new machine and am having problems.

I was able to install Ubuntu 22.04 and system-monitor-next on my new machine. However, I am unable to activate them.

Gnome is 42.5.
In extension-manager, I get an error that the meta is null.
Is there any way to fix this?

**Comment by mgalgs** [comment]
Do you have any additional logs? I assume you've already tried restarting gnome shell (`alt-f2 r`)

**Comment by h8672** [comment]
Problem solved with ``` apt install gir1.2-gtop-2.0 ``` on PopOS 22.04 with todays fresh installation.
Using it in ``` Dash to Panel ``` from ``` extensions.gnome.org ```

**Comment by mgalgs** [comment]
@nanbuwks can you please confirm if you're still having this issue after installing the dependencies mentioned above?

**Comment by janevert** [comment]
> Had the same issue, resolved by installing the dependencies. For me and Debian based: `apt install gir1.2-gtop-2.0 gir1.2-nm-1.0 gnome-system-monitor`

For me, this solution for Debian worked.
