### ISSUE TITLE
Gnome 44.1 is not supported

### ISSUE THREAD

**Issue by karolyi** [mgalgs/gnome-shell-system-monitor-applet#37]
Hey,

as it seems, Gnome 44.1 isn't supported:

![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/987055/5806fa22-c963-46da-8b42-f89b87e5ea77)

**Comment by 2lbj** [comment]
me too...
and I fix it for temp by edit "/usr/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/metadata.json" 

"shell-version": ["3.26", "3.28", "3.30", "3.32", "3.34", "3.36", "40", "41", "42", "43"],
-->
"shell-version": ["3.26", "3.28", "3.30", "3.32", "3.34", "3.36", "40", "41", "42", "43", "44"],

**Comment by 2lbj** [comment]
> Hey,
> 
> as it seems, Gnome 44.1 isn't supported:
> 
> ![image](https://user-images.githubusercontent.com/987055/243169244-5806fa22-c963-46da-8b42-f89b87e5ea77.png)

you can try do this https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/791

**Comment by mgalgs** [comment]
Are you sure you have the latest version of the extension? The one on the gnome extensions website has had support for 44 since April...

![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/152014/cfe3085c-6b18-4bda-ad92-33603510721f)

**Comment by 2lbj** [comment]
yes i saw that BUT my system is Linux Manjaro it still waiting for AUR sync this update
https://aur.archlinux.org/packages/gnome-shell-extension-system-monitor-next-git

**Comment by 2lbj** [comment]
> Are you sure you have the latest version of the extension? The one on the gnome extensions website has had support for 44 since April...
> 
> ![image](https://user-images.githubusercontent.com/152014/243449960-cfe3085c-6b18-4bda-ad92-33603510721f.png)

by the way I fount old version(r1173.fc9dc00-2) if edit "metadata.json" file to suport gnome-shell44 some times will be Memory Leak? did you know the reason? OR it's already be fix in latest version of the extension?

**Comment by mgalgs** [comment]
Not sure on the memory leak but yeah you'll either have to install it manually from the gnome extensions website or wait for the maintainer of that AUR package to bump it.

**Comment by mgalgs** [comment]
If you have additional details about a memory leak can you check [upstream](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet) to see if it's a known issue? If not can you please open a separate issue (ideally over at the upstream repo)?

**Comment by 2lbj** [comment]
> 不确定内存泄漏，但是是的，您要么必须从 gnome 扩展网站手动安装它，要么等待该 AUR 包的维护者来解决它。

yes i know.... sorry about "memory leak" I GOT reason that is [`gnome-shell-extension-openweather 121-1`](https://gitlab.com/skrewball/openweather)  leak I just disabled it then everything is GOOD wait for the maintainer update
