### ISSUE TITLE
AMD radeon support

### ISSUE THREAD

**Issue by antonio24073** [mgalgs/gnome-shell-system-monitor-applet#4]
Hi,
I saw that it isn't supporting amd video cards, but I prepared a script to easily implement this
`
sudo apt install radeontop
echo "password" | sudo -S radeontop -d --| grep -Po '((\d{1,3}).(\d{2})%)$' 
`

**Comment by antonio24073** [comment]
I worked out the idea better
I made a little workaround that works.
Modify and execute the bash file inside zip and replace line 40 of system-monitor@paradoxxx.zero.gmail.com/gpu_usage.sh 
with modified:  cat /home/antonio/gnome-radeon-monitor/radeontop-filtered.txt

[Uploading run (copy).sh.zip…]()

**Comment by mgalgs** [comment]
Hi @antonio24073! This repo is for packaging purposes only, all new development happens in the upstream repo, which is where you should file your request: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet

Thanks!
