### ISSUE TITLE
Big arrows

### ISSUE THREAD

**Issue by mgalgs** [mgalgs/gnome-shell-system-monitor-applet#41]
good work, it basically works

but there are still display errors

the big arrows:
![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/24853712/e9e5052c-b5c0-4482-b608-18de2c51d58b)

_Originally posted by @badsmoke in https://github.com/mgalgs/gnome-shell-system-monitor-applet/issues/38#issuecomment-1768196581_

**Comment by badsmoke** [comment]
are the settings still saved somewhere?

I have pulled again so that everything is default.

but it looks the same?

**Comment by mgalgs** [comment]
Huh, yeah I get the same thing though mine look a tiny bit nicer:

![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/152014/d9972e3e-ed8e-4d0d-aa7c-87db62b459a1)

I seem to remember seeing this in the past, so I don't think it's related to the GS 45 port. I think they're meant to be labels for download/upload. In any case, we should make them look nicer.

Looks like toggling the Net display style also messes with the labels of the other widgets... So something's off with the display style handling for sure:

https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/152014/8fa641ea-7df4-4e65-85f8-7caf989f18d9

**Comment by ZimbiX** [comment]
@mgalgs It looks to me like your labels might be being hidden because there's not enough room on the right hand side of the clock

**Comment by mgalgs** [comment]
Oh that makes a lot more sense... I was squinting at the code and didn't see anything special about net display handing...

I'm still in favor of a facelift for the up/down arrows!

**Comment by glerroo** [comment]
The problem is that PANEL_ICON_SIZE is undefined.

https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/55356f0bf600893a3ec6628939e37675d9d7e3b6/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L2361

this because PANEL_ICON_SIZE in GS45 is not exported.

Before GS45
`var PANEL_ICON_SIZE = 16;`

After GS45
`const PANEL_ICON_SIZE = 16;`

to be accessed from extension must be
`export const PANEL_ICON_SIZE = 16;`

**Comment by NVieville** [comment]
Hello,

Maybe `Panel.PANEL_ICON_SIZE` should be replaced by `16`, or a new local constant, line 2361 in the extension.js file.
There seems that all variables related to icons sizes were translated to local constant (not exported) in GS45 sources.

Cordially,


-- 
NVieville

**Comment by WhoChangedMyCode** [comment]
It does not seem to be a big problem, but I still hope that it can be fixed as soon as possible. Salute
