### ISSUE TITLE
Preferences page is a hot mess

### ISSUE THREAD

**Issue by mgalgs** [mgalgs/gnome-shell-system-monitor-applet#43]
The preferences page is currently barely usable, and needs to be seriously cleaned up. It might be nice to just do a full re-write using modern Adwaita widgets (e.g. [Adw.SwitchRow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.SwitchRow.html), [Adw.ComboRow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.ComboRow.html), etc.).

https://gjs.guide/extensions/development/preferences.html#gsettings

**Comment by glerroo** [comment]
What do you think about this organization of preferences pages.
Could this be okay?
![Schermata del 2023-10-19 16-45-56](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/73607126/43a67268-19a2-497c-a92e-8d305610038c)
![Schermata del 2023-10-19 16-46-09](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/73607126/3836385e-e3b2-4d28-9dfd-8101442d684f)
![Schermata del 2023-10-19 16-46-17](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/73607126/5bda789e-3e40-4a4a-963b-7c84a0dce45b)

**Comment by ZimbiX** [comment]
@glerroo Ooh, very nice

**Comment by mgalgs** [comment]
@glerroo that looks fantastic!

**Comment by glerroo** [comment]
Ok when i have some spare time i work on it.

**Comment by glerroo** [comment]
I'm working on this [Branch](https://github.com/glerroo/gnome-shell-system-monitor-applet/tree/prefs-rewrite), for now only the first page (general settings) is ready.
If someone want to test it.

**Comment by glerroo** [comment]
I found a little bug in extension.js
https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/14ab962ea1961c83e1a906d586292c075395ad5a/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L143C1-L146C2
Line 145 must be build_menu_info(this.extension);

**Comment by glerroo** [comment]
Third page completed (widget preferences).
Now the more complicated for me (widget position), i don't have experience with dnd.

**Comment by mgalgs** [comment]
> I found a little bug in extension.js

Great find. Fixed in `master`.

**Comment by glerroo** [comment]
Second page completed (widget position).
Now is time to clean-up and remove unnecessary code.

**Comment by glerroo** [comment]
I think is all done and working fine.
I created a PR #45.
