### ISSUE TITLE
Menu is blank

### ISSUE THREAD

**Issue by BxOxSxS** [mgalgs/gnome-shell-system-monitor-applet#44]
After latest updates (I am not sure what commit exactly but yesterday it was working fine when testing PR to support gnome45) the menu is blank.
![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/47485031/4b5cf136-d490-4f44-8520-2837949286b3)
Here are mine settings:
```bash
$ dconf dump /org/gnome/shell/extensions/system-monitor/
[/]
battery-show-text=false
cpu-display=false
cpu-individual-cores=true
cpu-show-text=true
cpu-style='digit'
disk-show-text=false
disk-style='digit'
disk-usage-style='none'
fan-sensor-file='/sys/class/hwmon/hwmon3/fan1_input'
fan-show-text=false
fan-style='digit'
freq-show-menu=true
freq-style='digit'
gpu-show-menu=true
gpu-show-text=false
gpu-style='digit'
memory-display=false
memory-show-text=false
memory-style='digit'
net-display=false
net-show-text=false
net-style='digit'
swap-show-text=false
swap-style='digit'
thermal-sensor-file='/sys/class/hwmon/hwmon1/temp1_input'
thermal-show-text=false
thermal-style='digit'
```
In short these settings are just displaying everything as text only when clicking on extension. 
`journalctl -xe /usr/bin/gnome-shell` does not show any error realated to extension.

**Comment by mgalgs** [comment]
Well that's strange... Based on the timing of [your comment](https://github.com/mgalgs/gnome-shell-system-monitor-applet/pull/39#issuecomment-1769032869) on the PR yesterday this should be the difference between what you tested and what's currently on in `master`:

https://github.com/mgalgs/gnome-shell-system-monitor-applet/compare/e881d934d3d3ffd237f57e163239991c7a98c7d7..master

- Subdirectory rename (maybe there's a stale link sitting around or something?)
- New approach for CPU positioning (if there was an issue here I would expect an error message)
- Docs and build changes (shouldn't affect extension behavior)

So I'm a bit at a loss... :thinking: Just to check, have you tried fully removing the extension, restarting your session, reinstalling fresh, restart your session again?

**Comment by BxOxSxS** [comment]
Yes I tried to full reinstall and reset. I did some testing and looks like the fault commit is b53c0fe61bbaedc4255a81a60735cb331671c9c2. It's does not display text even on default settings exept the text on disk pie
![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/47485031/60941fc4-1415-4baa-8261-9f5d3e56a2ec)

**Comment by mgalgs** [comment]
That’s super helpful, thanks. I’ll take a closer look in a bit here.

**Comment by mgalgs** [comment]
Yeeeeah you nailed it on that commit. I must have been in autopilot mode not paying attention when testing... :facepalm: Should be fixed now.
