### ISSUE TITLE
CPU frequencty is not display for 12th Gen Intel® Core™ i5-1235U

### ISSUE THREAD

**Issue by koroki** [mgalgs/gnome-shell-system-monitor-applet#46]
I'm not sure if it is only a problem of my CPU or not, but this option now did not show any information any more. The target appears in the menu or in the bar, but with no information.

**Comment by koroki** [comment]
![Captura de pantalla de 2023-10-31 17-06-49](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/8328312/cb4b47d2-b9c2-4efc-8607-fcc24f5255d9)

**Comment by mgalgs** [comment]
Yeah I'm seeing the same thing here. I'm a bit swamped at the moment but can look at it in a few days unless someone beats me to it:

https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/4438965f0d4db17f304fb21daf56d99ba74bd48a/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L1551-L1620

**Comment by mgalgs** [comment]
> let num_cpus = GTop.glibtop_get_sysinfo().ncpu; 

Need to verify that this is still working. `sm_log` is always an option, but would be nice to use looking glass for this. Anyone know how to access `GTop` from a looking glass session? Can't do `import GTop from "gi://GTop";` in looking glass...

**Comment by glerroo** [comment]
You can use a gjs console.

![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/73607126/2b5a7df5-30ca-4761-9068-f66d2e903557)

**Comment by mgalgs** [comment]
Aah nice... And hey, accessing it via `imports.gi.GTop` works from looking glass as well :+1:

**Comment by koroki** [comment]
Thanks for all the work and for revive this extension!

**Comment by mgalgs** [comment]
Oh hold on mine's actually working:

![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/152014/a2cd36a4-1a92-40ca-87d6-c201bf082724)

I was testing inside a VM before.

Can you please run `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` and share the results?

**Comment by koroki** [comment]
I checked and it is working. The problem is, when I activated, the extension does not show any information. But if you leave the option activated and restart the system, the frequency is shown.
