### ISSUE TITLE
Broken setting screen after latest extensions.gnome.org update - version 60

### ISSUE THREAD

**Issue by Alg3r** [mgalgs/gnome-shell-system-monitor-applet#47]
After latest update settings screen is broken.
The reported version is 60.
I tried dconf reset -f /org/gnome/shell/extensions/system-monitor/ - still the same problem.
I switched to latest code from repository and the same problem.

Screenshots of menu:
![obraz](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/1842014/6def095c-db7c-4e15-a896-93ac16946ad1)
![obraz](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/1842014/f18a363c-3800-44db-a5bf-9541a1a85976)

The message log is as follow:
```
TypeError: this.settings is undefined

Stack trace:
  SMExpanderRow@file:///home/mateusz/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/prefs.js:599:21
  SMWidgetPrefsPage/<@file:///home/mateusz/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/prefs.js:690:24
  SMWidgetPrefsPage@file:///home/mateusz/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/prefs.js:689:21
  fillPreferencesWindow@file:///home/mateusz/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/prefs.js:707:37
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:36:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:21:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:12:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by NVieville** [comment]
Hello,

Maybe, this issue should be fixed by replacing the string `this.settings` by `this._settings` lines 541 and 599 of the prefs.js file.

Cordially,


-- 
NVieville

**Comment by Alg3r** [comment]
I did proposed change in two places in prefs.js and so far it works correctly.

**Comment by mgalgs** [comment]
Great catch! Fix submitted. I've been testing under a VM since I'm still using X11 and [restarting gnome shell without logout/login is currently broken](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7050), so never encountered this...
