### ISSUE TITLE
Install instructions: Alt+F2 & r crashed my box

### ISSUE THREAD

**Issue by PurryPlatypus** [mgalgs/gnome-shell-system-monitor-applet#49]
I'd like there to be a warning in the install instructions; Alt+F2 & r (restarting the Gnome GUI/Shell) might fail unrecoverably.

Well, it failed on my box - ~2 days of uptime, Ubuntu 23.10 with lots of running apps, like MPV, Firefox, virt-manager, GNUcash, and then some. I've had the KDE file manager Dolphin running, also. I'd call this a convoluted / complicated runtime state.

It crashed, and i had to reboot the whole box, and all the VMs.

My recommendation; adjust the install instructions and manage expectations, so users render their box into a safe (less unpredictable) state before attempting an install. A reboot, for good measure, seems to be good advice in any case.

Edit: i'd like to thank you, for taking over the maintenance of this package.

**Comment by glerroo** [comment]
I think this is a Gnome Shell issue [Gnome Shell crashes or just exits, without anything in logs.](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7158).
In my box Alt+F2 & r work only if there are no applications open.

**Comment by mgalgs** [comment]
I believe this is the `Alt-F2 r` bug: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7050

I agree that we should update the description until this is fixed. In the meantime, please go vote on that gitlab issue!

**Comment by mgalgs** [comment]
Also, we should fix the install/update error... :point_right: #50
