### ISSUE TITLE
Possibility to make the Net icons smaller

### ISSUE THREAD

**Issue by ixevix** [mgalgs/gnome-shell-system-monitor-applet#52]
Would it be possible to make the icons for the net view smaller? Currently they take up so much extra space.

![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/820718/ed1e5b28-95c7-449a-b394-75072c0579b4)

They are visible when you enable Display style "digit" or "both".

![image](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/820718/2dd1720c-06ee-486f-948e-de42e388bd25)

**Comment by ZimbiX** [comment]
Seems like a duplicate of https://github.com/mgalgs/gnome-shell-system-monitor-applet/issues/41, although it was supposed to have been fixed

**Comment by ixevix** [comment]
Yeah seems it was fixed. Didn't see the other issue. Thanks! I updated to newer version and it's fixed now.
