### ISSUE TITLE
Constant error in journal

### ISSUE THREAD

**Issue by morphheus** [mgalgs/gnome-shell-system-monitor-applet#56]
I'm getting the following error every few seconds in the journalctl log:

`Nov 27 09:50:01 davidtlr gnome-shell[1379]: JS ERROR: Gio.IOErrorEnum: Error reading from file: Invalid argument
                                            refresh/<@file:///home/dave/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2070:35
                                            @resource:///org/gnome/shell/ui/init.js:21:20
`

The extension seems to be working fine, I haven not noticed any faulty behavior. 
My knowledge of JS is nonexistent, so I'm not sure how how to either fix or silence this error, since its spoiling the journalctl log.

Any ideas?

**Comment by ZimbiX** [comment]
Related: https://github.com/mgalgs/gnome-shell-system-monitor-applet/issues/35

**Comment by morphheus** [comment]
Sweet, seems it was stuck on a non-existent temperature sensor file.

Closing this.
