### ISSUE TITLE
[NixOS] Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found

### ISSUE THREAD

**Issue by kropochev** [mgalgs/gnome-shell-system-monitor-applet#57]
Ubuntu 23.10
Gnome 45.1

After install extension from https://extensions.gnome.org/extension/3010/system-monitor-next/ getting error:

![Screenshot from 2023-11-30 21-17-39](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/8565494/01e6b149-e345-47d3-a513-0364803bf36a)

```
$ sudo apt install gir1.2-gtop-2.0 gir1.2-nm-1.0 gir1.2-clutter-1.0 gnome-system-monitor
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gir1.2-gtop-2.0 is already the newest version (2.40.0-2build3).
gir1.2-nm-1.0 is already the newest version (1.44.2-1ubuntu1.2).
gir1.2-clutter-1.0 is already the newest version (1.26.4+git2779b932+dfsg-5).
gnome-system-monitor is already the newest version (45.0.2-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by naturecodevoid** [comment]
Also getting this on NixOS 24.05 beta.

**Comment by kropochev** [comment]
I solved this problem by rebooting the PC.

**Comment by naturecodevoid** [comment]
Tried installing libgtop and restarting my machine, no success. Will try installing gtop itself now

**Comment by naturecodevoid** [comment]
Wasn't able to fix this, but the [Vitals](https://extensions.gnome.org/extension/1460/vitals/) extension worked just fine as a replacement.

**Comment by mgalgs** [comment]
@naturecodevoid I did a quick search of NixOS packages and wasn't able to find any gir1.2 libgtop packages. I guess we'd need to provide a fallback when not installed (which must be what Vitals is doing).

I'm tempted to close this but will leave it open in case anyone else wants to vote for NixOS support.

**Comment by naturecodevoid** [comment]
Yes, I agree. NixOS does not seem to have any gir binding packages.

**Comment by mgalgs** [comment]
Added `[NixOS]` to the title. If anyone on Nix gets the extension working (I assume a gir bindings package will land in Nix at some point) please drop a comment!

**Comment by JollyDevelopment** [comment]
I got this to work accidentally, because of what https://github.com/AstraExt/astra-monitor said to do to get theirs to work.

```
environment.systemPackages = with pkgs; [
    ....
   gnomeExtensions.system-monitor-next
   libgtop
   ....
   ];

  environment.variables = {
    GI_TYPELIB_PATH = "/run/current-system/sw/lib/girepository-1.0";
  };
```

After I did that and rebooted, system-monitor-next just popped up happy as you can be. :-)
