### ISSUE TITLE
Support for multi GPU setups

### ISSUE THREAD

**Issue by menoos** [mgalgs/gnome-shell-system-monitor-applet#6]
It would be really handy if there was an option to display stats for all GPUs available in the machine.
Or maybe to pick a specific one as a first step.

**Comment by mgalgs** [comment]
Hi @menoos! This repo is for packaging purposes only, all new development happens in the upstream repo, which is where you should file your request: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet

Thanks!
