### ISSUE TITLE
Gnome 46 support

### ISSUE THREAD

**Issue by marxin** [mgalgs/gnome-shell-system-monitor-applet#61]
Again, I am a passionate Extension user, I just love it ;)

Just recently, I switched to Gnome 46 Alpha (as I face a strange VTE/gnome-terminal issues with monitor) and I noticed the extension does not work right now (once I added `46` to the list of supported versions):

```
Type.Error: this.actor.add_actor is not a function
```

**Comment by rathann** [comment]
https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/master/system-monitor-next%40paradoxxx.zero.gmail.com/metadata.json#L2 still says 45 only.

**Comment by mgalgs** [comment]
@rathann yeah, we still don't have GS 46 support. I haven't had time to set up a GS 46 VM. PRs are welcome!

**Comment by NVieville** [comment]
Hello,

Maybe this should be helpful:

https://gjs.guide/extensions/upgrading/gnome-shell-46.html#clutter-container

As I don't have GS 46 yet on my laptop (every day work machine), I can't say if the link above is the way to follow to get this extension compatible with it.

Cordially,


-- 
NVieville

**Comment by glerroo** [comment]
I have added a pull request with GS 46 support.
@marxin can you test if #64 work correctly.

**Comment by mgalgs** [comment]
Fixed-by: #64
