### ISSUE TITLE
Setting usage style to "none" still shows usage in popup

### ISSUE THREAD

**Issue by jcassee** [mgalgs/gnome-shell-system-monitor-applet#66]
As per the title, I had expected to be able to disable the large circle diagram for disk usage, but the usage style setting does not seem to do anything?

**Comment by glerroo** [comment]
Have you tried logout and login again in gnome shell.

**Comment by jcassee** [comment]
:smile:  Indeed, that fixed it. Appologies, the rest of the settings were applied immediately, I must have missed that in the readme. Thank you!
