### ISSUE TITLE
Error: Tried to construct an object without a GType

### ISSUE THREAD

**Issue by dbear496** [mgalgs/gnome-shell-system-monitor-applet#7]
I recently updated system-monitor-next via Firefox, and now the extension won't start. When I look in the Extensions app, it says `Error: Tried to construct an object without a GType`. I tried reinstalling the extension and rebooting, but the extension still does not start. 

Info:
system-monitor-next: 36
GNOME: 40.2.0
OS: Ubuntu 21.10

**Comment by mgalgs** [comment]
Hello, seems like a bug but we don't do any development in this repo. You'll want to submit this to the upstream project: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet

**Comment by mgalgs** [comment]
This repo exists for the sole purpose of continuous release off of the upstream master branch

**Comment by dbear496** [comment]
Ah. Sorry about that. I submitted the issue on the upstream branch: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/713.
