### ISSUE TITLE
Version 67 on extensions.gnome.org is missing common.js

### ISSUE THREAD

**Issue by StephGbzh** [mgalgs/gnome-shell-system-monitor-applet#75]
I got a notification to upgrade the extension but even after a logout/login it fails.
It turns out that the new version 67 on extensions.gnome.org is missing the file common.js
Adding it manually from the github repo and logout/login make it work again.

**Comment by ZimbiX** [comment]
Thanks for the report! I've just submitted a PR which should fix this

**Comment by ShrirajHegde** [comment]
For those who have this issue, and need a quick fix,


```
curl https://raw.githubusercontent.com/mgalgs/gnome-shell-system-monitor-applet/master/system-monitor-next%40paradoxxx.zero.gmail.com/common.js > ~/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/common.js
```

**Comment by mgalgs** [comment]
Holy smokes! Thanks for the quick turnaround on a patch, @ZimbiX. As mentioned in the PR, I'm really itching for some CI on this thing... #77 has been filed.

**Comment by mgalgs** [comment]
A new build has been submitted to g.s.o with the fix, btw.
