### ISSUE TITLE
[Fedora SilverBlue] Fan and Thermal sensors not showing up after recent update

### ISSUE THREAD

**Issue by madagaskarsky** [mgalgs/gnome-shell-system-monitor-applet#79]
OS: Fedora Linux 39.20240429.0 (Silverblue)
Hardware: Apple Inc. MacBookPro11,3 Intel® Core™ i7-4980HQ × 8
Gnome: 45.5

The applet updated today. After the update multiple Fan sensor and thermal sensor options have vanished. Now the thermal sensor only provides sensor updates from the nouveau, battery and the cpu. Image shows the applet appearance menu showing the lack of sensors options.

Love your work.
![Screenshot from 2024-05-05 02-32-50](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/13730211/f34d03a0-cc0f-4d52-9a30-8cdc5698c655)

**Comment by mgalgs** [comment]
Thanks for the report, and yes we did recently rework the sensor handling. Ideally it should all work out of the box if your sensor drivers are registering with the `hwmon` framework in the kernel. Are the missing sensors present in sysfs? Can you please provide the output of the following commands:

```
for f in /sys/class/hwmon/*/name; do echo "$f -> $(cat $f)"; done
```

```
for f in /sys/class/hwmon/*/*_label; do echo "$f -> $(cat $f)"; done
```

Cc: @rschupp

**Comment by madagaskarsky** [comment]
The response for this 

>for f in /sys/class/hwmon/*/name; do echo "$f -> $(cat $f)"; done

is 

    /sys/class/hwmon/hwmon0/name -> ADP1
    /sys/class/hwmon/hwmon1/name -> nouveau
    /sys/class/hwmon/hwmon2/name -> BAT0
    /sys/class/hwmon/hwmon4/name -> coretemp


and 

>for f in /sys/class/hwmon/*/*_label; do echo "$f -> $(cat $f)"; done

is

    /sys/class/hwmon/hwmon1/in0_label -> GPU core
    /sys/class/hwmon/hwmon2/temp1_label -> temp
    /sys/class/hwmon/hwmon4/temp1_label -> Package id 0
    /sys/class/hwmon/hwmon4/temp2_label -> Core 0
    /sys/class/hwmon/hwmon4/temp3_label -> Core 1
    /sys/class/hwmon/hwmon4/temp4_label -> Core 2
    /sys/class/hwmon/hwmon4/temp5_label -> Core 3

Thank you for your prompt response, I was not expecting that.

**Comment by mgalgs** [comment]
Interesting... Could you please collect output from a couple more commands:

```
tree -l -L 2 /sys/class/hwmon/
```

and

```
for f in /sys/class/hwmon/*/*_input; do echo "$f -> $(cat $f)"; done
```

Are you missing anything other than ADP1?

**Comment by madagaskarsky** [comment]
Of course.

>tree -l -L 2 /sys/class/hwmon/
    
      /sys/class/hwmon/
    ├── hwmon0 -> ../../devices/platform/ACPI0003:00/power_supply/ADP1/hwmon0
    │   ├── device -> ../../ADP1
    │   ├── name
    │   ├── power
    │   ├── subsystem -> ../../../../../../class/hwmon  [recursive, not followed]
    │   └── uevent
    ├── hwmon1 -> ../../devices/pci0000:00/0000:00:01.0/0000:01:00.0/hwmon/hwmon1
    │   ├── device -> ../../../0000:01:00.0
    │   ├── in0_input
    │   ├── in0_label
    │   ├── in0_max
    │   ├── in0_min
    │   ├── name
    │   ├── power
    │   ├── subsystem -> ../../../../../../class/hwmon  [recursive, not followed]
    │   ├── temp1_auto_point1_pwm
    │   ├── temp1_auto_point1_temp
    │   ├── temp1_auto_point1_temp_hyst
    │   ├── temp1_crit
    │   ├── temp1_crit_hyst
    │   ├── temp1_emergency
    │   ├── temp1_emergency_hyst
    │   ├── temp1_input
    │   ├── temp1_max
    │   ├── temp1_max_hyst
    │   ├── uevent
    │   └── update_interval
    ├── hwmon2 -> ../../devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:61/PNP0C09:00/ACPI0001:00/ACPI0002:00/power_supply/BAT0/hwmon2
    │   ├── curr1_average
    │   ├── curr1_input
    │   ├── device -> ../../BAT0
    │   ├── in0_input
    │   ├── name
    │   ├── power
    │   ├── subsystem -> ../../../../../../../../../../../class/hwmon  [recursive, not followed]
    │   ├── temp1_input
    │   ├── temp1_label
    │   └── uevent
    ├── hwmon3 -> ../../devices/platform/applesmc.768/hwmon/hwmon3
    │   ├── device -> ../../../applesmc.768
    │   ├── power
    │   ├── subsystem -> ../../../../../class/hwmon  [recursive, not followed]
    │   └── uevent
    └── hwmon4 -> ../../devices/platform/coretemp.0/hwmon/hwmon4
        ├── device -> ../../../coretemp.0
        ├── name
        ├── power
        ├── subsystem -> ../../../../../class/hwmon  [recursive, not followed]
        ├── temp1_crit
        ├── temp1_crit_alarm
        ├── temp1_input
        ├── temp1_label
        ├── temp1_max
        ├── temp2_crit
        ├── temp2_crit_alarm
        ├── temp2_input
        ├── temp2_label
        ├── temp2_max
        ├── temp3_crit
        ├── temp3_crit_alarm
        ├── temp3_input
        ├── temp3_label
        ├── temp3_max
        ├── temp4_crit
        ├── temp4_crit_alarm
        ├── temp4_input
        ├── temp4_label
        ├── temp4_max
        ├── temp5_crit
        ├── temp5_crit_alarm
        ├── temp5_input
        ├── temp5_label
        ├── temp5_max
        └── uevent
    
    21 directories, 54 files

>for f in /sys/class/hwmon/*/*_input; do echo "$f -> $(cat $f)"; done

    /sys/class/hwmon/hwmon1/in0_input -> 850
    /sys/class/hwmon/hwmon1/temp1_input -> 63000
    /sys/class/hwmon/hwmon2/curr1_input -> 0
    /sys/class/hwmon/hwmon2/in0_input -> 12728
    /sys/class/hwmon/hwmon2/temp1_input -> 38600
    /sys/class/hwmon/hwmon4/temp1_input -> 72000
    /sys/class/hwmon/hwmon4/temp2_input -> 71000
    /sys/class/hwmon/hwmon4/temp3_input -> 69000
    /sys/class/hwmon/hwmon4/temp4_input -> 71000
    /sys/class/hwmon/hwmon4/temp5_input -> 67000

I am not aware what ADP1 means, so I don't know. I had the multiple thermal options and the two fan options before the update, and then no fan options and limited thermal options.

**Comment by rschupp** [comment]
`hwmon3` is probably the Apple System Management Controller which has (among other stuff) temperature and fan sensors, `hwmon0` might be the PCH. 
Can you post the output of:
```
tree -l -L 1 /sys/class/hwmon/hwmon[03]/device
```
so we can see if there are sensor files below the `device` subdirectory (looking there was removed in 1101eba).

**Comment by madagaskarsky** [comment]
>tree -l -L 1 /sys/class/hwmon/hwmon[03]/device

    /sys/class/hwmon/hwmon0/device
      ├── device -> ../../../ACPI0003:00
      ├── hwmon0
      ├── online
      ├── power
      ├── subsystem -> ../../../../../class/power_supply
      ├── type
      ├── uevent
      └── wakeup31
      /sys/class/hwmon/hwmon3/device
      ├── driver -> ../../../bus/platform/drivers/applesmc
      ├── driver_override
      ├── fan1_input
      ├── fan1_label
      ├── fan1_manual
      ├── fan1_max
      ├── fan1_min
      ├── fan1_output
      ├── fan1_safe
      ├── fan2_input
      ├── fan2_label
      ├── fan2_manual
      ├── fan2_max
      ├── fan2_min
      ├── fan2_output
      ├── fan2_safe
      ├── hwmon
      ├── key_at_index
      ├── key_at_index_data
      ├── key_at_index_data_length
      ├── key_at_index_name
      ├── key_at_index_type
      ├── key_count
      ├── leds
      ├── light
      ├── modalias
      ├── name
      ├── power
      ├── subsystem -> ../../../bus/platform
      ├── temp10_input
      ├── temp10_label
      ├── temp11_input
      ├── temp11_label
      ├── temp12_input
      ├── temp12_label
      ├── temp13_input
      ├── temp13_label
      ├── temp14_input
      ├── temp14_label
      ├── temp15_input
      ├── temp15_label
      ├── temp16_input
      ├── temp16_label
      ├── temp17_input
      ├── temp17_label
      ├── temp18_input
      ├── temp18_label
      ├── temp19_input
      ├── temp19_label
      ├── temp1_input
      ├── temp1_label
      ├── temp20_input
      ├── temp20_label
      ├── temp21_input
      ├── temp21_label
      ├── temp22_input
      ├── temp22_label
      ├── temp23_input
      ├── temp23_label
      ├── temp24_input
      ├── temp24_label
      ├── temp25_input
      ├── temp25_label
      ├── temp26_input
      ├── temp26_label
      ├── temp27_input
      ├── temp27_label
      ├── temp28_input
      ├── temp28_label
      ├── temp29_input
      ├── temp29_label
      ├── temp2_input
      ├── temp2_label
      ├── temp30_input
      ├── temp30_label
      ├── temp31_input
      ├── temp31_label
      ├── temp32_input
      ├── temp32_label
      ├── temp33_input
      ├── temp33_label
      ├── temp34_input
      ├── temp34_label
      ├── temp35_input
      ├── temp35_label
      ├── temp36_input
      ├── temp36_label
      ├── temp37_input
      ├── temp37_label
      ├── temp38_input
      ├── temp38_label
      ├── temp39_input
      ├── temp39_label
      ├── temp3_input
      ├── temp3_label
      ├── temp40_input
      ├── temp40_label
      ├── temp4_input
      ├── temp4_label
      ├── temp5_input
      ├── temp5_label
      ├── temp6_input
      ├── temp6_label
      ├── temp7_input
      ├── temp7_label
      ├── temp8_input
      ├── temp8_label
      ├── temp9_input
      ├── temp9_label
      └── uevent
      
      12 directories, 108 files

**Comment by rschupp** [comment]
@madagaskarsky  Thanks, that confirms it: the "missing" `{temp,fan}*_{input,label}` files are in the `device` subdirectory. Time to revert https://github.com/mgalgs/gnome-shell-system-monitor-applet/commit/1101ebaf22ffeeb5f438d38fc0c27e61922a5bff.

**Comment by rschupp** [comment]
@madagaskarsky Can you test with #80?

**Comment by madagaskarsky** [comment]
Yes, it works now. Thank you! I will wait for the official update, until then I'll use this one.

Image shows the preference window with all the options back.

![Screenshot from 2024-05-08 15-53-07](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/13730211/6670999a-5291-4a6f-ba0c-def7a0b1ee54)

**Comment by rschupp** [comment]
@madagaskarsky  Thanks for testing. Final question: what's the output of
```
cat /sys/class/hwmon/hwmon3/device/name
```
Maybe we can do better than "hwmon3" as the first part of the sensor labels.

**Comment by madagaskarsky** [comment]
Sure,

>cat /sys/class/hwmon/hwmon3/device/name

    applesmc

**Comment by rschupp** [comment]
@madagaskarsky  I updated #80: "hwmon3 - Th1H" etc should now show as "applesmc - Th1H" (which should also help if the kernel ever decides to renumber hwmon's).
