### ISSUE TITLE
[Ubuntu 24.04] Error: Requiring GTop

### ISSUE THREAD

**Issue by Voronsky** [mgalgs/gnome-shell-system-monitor-applet#84]
Hey there,

 I came across the extension and wanted to check it out! I encountered an error despite installing the required packages listed in the `README` for Ubuntu. 
 
 `gir1.2-gtop-2.0 gir1.2-nm-1.0 gir1.2-clutter-1.0 gnome-system-monitor`

Here are the errors I got.

![Screenshot from 2024-05-30 10-42-59](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/1648245/601893e3-0e4e-4954-8bda-9ae7220310bc)

I was able to fix it by installing this additional libgtop package `libgtop2-dev`  and rebooting,  which I found from another system monitor tool which also required libgtop: https://github.com/elvetemedve/gnome-shell-extension-system-monitor/wiki/Installation#dependencies

but now it works:
![Screenshot from 2024-05-30 11-05-00](https://github.com/mgalgs/gnome-shell-system-monitor-applet/assets/1648245/7a880346-4f35-40de-b62a-5ab190ea9c75)

Not sure if maybe I was just a unique case.

**Comment by rschupp** [comment]
@Voronsky Nope, `gir1.2-gtop-2.0` is all that's required, it just contains the `Typelib file` that's mentioned in the error message, see the [Ubuntu file list](https://packages.ubuntu.com/focal/amd64/gir1.2-gtop-2.0/filelist) or check yourself with `dpkg -L gir1.2-gtop-2.0`. 
`libgtop2-dev` depends on `gir1.2-gtop-2.0` and contains some include files plus the `.gir` file for `libgtop` which is **not** used by runtime gobject introspection.

**Comment by Voronsky** [comment]
Gotcha, that makes sense! It is very likely that I should have just rebooted it after installing the proper packages, which would have fixed my issue then, but I confused two things. Thanks!
