### ISSUE TITLE
File conflict with official GNOME Shell extension

### ISSUE THREAD

**Issue by jbicha** [mgalgs/gnome-shell-system-monitor-applet#89]
gnome-shell-extensions has included a system-monitor extension since version 46. This creates a file conflict with this extension since both extensions can't include this file:

`/usr/share/glib-2.0/schemas/org.gnome.shell.extensions.system-monitor.gschema.xml`

Since gnome-shell-extensions is official, I believe this extension will need to use a different gsetting schema.

**Comment by ZimbiX** [comment]
See https://github.com/mgalgs/gnome-shell-system-monitor-applet/pull/65
