### ISSUE TITLE
"Meta is null" error

### ISSUE THREAD

**Issue by ilvidel** [mgalgs/gnome-shell-system-monitor-applet#95]
I got the following error on `/var/log/syslog` when trying to install:

```
Oct  2 10:06:32 2fcpm53 gnome-shell[3073]: JS ERROR: Extension system-monitor-next@paradoxxx.zero.gmail.com: TypeError: meta is null
012_patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:76:13
012_patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:85:18
012SystemMonitor_smDialog@/home/ignaciod/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:292:32
012enable@/home/ignaciod/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2416:23
012_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:183:32
012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:384:26
012_onInstallButtonPressed@resource:///org/gnome/shell/ui/extensionDownloader.js:278:35
012Async*addButton/<@resource:///org/gnome/shell/ui/dialog.js:130:41
```

Funnily, I can open the extension settings, via gnome-shell-extension-manager

My configuration is:
- Ubuntu 22.04
- Gnome-shell 42.9

**Comment by mgalgs** [comment]
Ah the pesky "meta is null" problem... There are a few root causes for this, we could handle it more gracefully but updating the extension for old versions of Gnome Shell is pretty far down on the priority list...

Please try the solutions described in #36 and/or #60 and let us know how it goes!

**Comment by ilvidel** [comment]
Ah, apologies. I didn't think of looking in the closed issues :disappointed: 
I tried installing `gir1.2-gtop-2.0` as suggested in #36 (the other dependencies were already present), with no luck.

Then I thought I might need to reload gnome, so tried that and got a "restart not available on Wayland". And that's when it hit me. I didn't know I was running Wayland (the laptop was pre-configured for me, didn't think of that).

Switching to Xorg fixed the issue!
