### ISSUE TITLE
Make System-Monitor configurable

### ISSUE THREAD

**Issue by Sythelux** [mgalgs/gnome-shell-system-monitor-applet#96]
I love the feature on just clicking on the applet and click "system-monitor"

but I recently switch to mission center (https://missioncenter.io/) and I'd love to have the application that opens when clicking on that drop-down button configurable. the button name can stay the same as I'm technical still use a similar tool.

**Comment by ZimbiX** [comment]
Thanks for the tip about Mission Center! Looks great. So, good idea

**Comment by mgalgs** [comment]
That does look fantastic and I'm totally on board with making the "System Monitor" action configurable! I'll try to knock it out when I can but PRs are welcome if anyone beats me to it! :fist_oncoming:

**Comment by mgalgs** [comment]
WIP is available on the `[custom-system-monitor-app](https://github.com/mgalgs/gnome-shell-system-monitor-applet/tree/custom-system-monitor-app)` branch. It's based on top of the branch for #98 so we need to wait for that to merge before we can merge this guy.

https://github.com/user-attachments/assets/bf13ff11-8586-410f-8fab-8917d666308c

**Comment by Sythelux** [comment]
I finally upgraded Pop!_OS to 24.04 and installed gnome and was able to use the version that has this feature. Thank you a lot everyone!
