### ISSUE TITLE
Error "Meta..." -no, solved

### ISSUE THREAD

**Issue by AsusA15** [mgalgs/gnome-shell-system-monitor-applet#97]
In fact, it has been solved! i haven't RTFM! installing a couple of libs, And restart the shell did it!
It reminds me of 'same' sys monitor available with WindowMaker (sometimes ago...)

Thank You (x100) !

**Comment by mgalgs** [comment]
You've inspired me to revamp the README (and include the "meta is null" error message there for searchability), which is something I've been meaning to do for a while! :1st_place_medal:
